version: '2.2'
services:
  db:
    build:
      context: ""
    container_name: keep_db
    image: mysql:5.7
    ports:
      - "3305:3306"
    env_file:
      - docker.env
  app:
    build:
      context: ""
    volumes:
      - ./:/usr/src/keep_be
    container_name: keep_be
    ports:
      - "8000:8080"
    tty: true
    depends_on:
      - db