// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"context"
	"github.com/google/wire"
	"hackernews-api/graph"
	"hackernews-api/internal/config"
	"hackernews-api/internal/pkg/db/migrations/mysql"
	"hackernews-api/repositories"
	"hackernews-api/services/auth"
	"hackernews-api/services/note"
	"hackernews-api/services/user_config"
	"hackernews-api/services/users"
	"hackernews-api/test"
)

// Injectors from wire.go:

func GetApp() (*App, error) {
	configConfig := config.GetCfg()
	dbProvider := database.InitDB(configConfig)
	userRepository := &repositories.UserRepository{
		DbProvider: dbProvider,
	}
	authRepository := repositories.AuthRepository{
		DbProvider: dbProvider,
	}
	authService := &auth.AuthService{
		AuthRepository: authRepository,
	}
	userService := &users.UserService{
		DbProvider:     dbProvider,
		UserRepository: userRepository,
		AuthService:    authService,
	}
	noteRepository := &repositories.NoteRepository{
		DbProvider:     dbProvider,
		UserRepository: userRepository,
	}
	noteService := &note.NoteService{
		NoteRepository: noteRepository,
	}
	userConfigRepository := repositories.UserConfigRepository{
		DbProvider:     dbProvider,
		UserRepository: userRepository,
	}
	userConfigService := &user_config.UserConfigService{
		DbProvider:           dbProvider,
		UserConfigRepository: userConfigRepository,
	}
	repositoriesUserConfigRepository := &repositories.UserConfigRepository{
		DbProvider:     dbProvider,
		UserRepository: userRepository,
	}
	resolver := graph.Resolver{
		IUserService:          userService,
		INoteService:          noteService,
		IAuthService:          authService,
		IUserConfigService:    userConfigService,
		IUserRepository:       userRepository,
		INoteRepository:       noteRepository,
		IUserConfigRepository: repositoriesUserConfigRepository,
	}
	app := &App{
		Resolver:          resolver,
		DbProvider:        dbProvider,
		UserService:       userService,
		NoteService:       noteService,
		AuthService:       authService,
		UserConfigService: userConfigService,
	}
	return app, nil
}

func GetTestApp() (*test.TestApp, error) {
	context := getTestContext()
	dbProvider := test.InitMockDB()
	userRepository := &repositories.UserRepository{
		DbProvider: dbProvider,
	}
	authRepository := repositories.AuthRepository{
		DbProvider: dbProvider,
	}
	authService := &auth.AuthService{
		AuthRepository: authRepository,
	}
	userService := &users.UserService{
		DbProvider:     dbProvider,
		UserRepository: userRepository,
		AuthService:    authService,
	}
	noteRepository := &repositories.NoteRepository{
		DbProvider:     dbProvider,
		UserRepository: userRepository,
	}
	noteService := &note.NoteService{
		NoteRepository: noteRepository,
	}
	userConfigRepository := repositories.UserConfigRepository{
		DbProvider:     dbProvider,
		UserRepository: userRepository,
	}
	userConfigService := &user_config.UserConfigService{
		DbProvider:           dbProvider,
		UserConfigRepository: userConfigRepository,
	}
	repositoriesUserConfigRepository := &repositories.UserConfigRepository{
		DbProvider:     dbProvider,
		UserRepository: userRepository,
	}
	resolver := &graph.Resolver{
		IUserService:          userService,
		INoteService:          noteService,
		IAuthService:          authService,
		IUserConfigService:    userConfigService,
		IUserRepository:       userRepository,
		INoteRepository:       noteRepository,
		IUserConfigRepository: repositoriesUserConfigRepository,
	}
	testAppOptions := &test.TestAppOptions{
		Resolver: resolver,
	}
	testApp := test.InitTestApp(context, testAppOptions)
	return testApp, nil
}

// wire.go:

type App struct {
	Resolver          graph.Resolver
	DbProvider        *database.DbProvider
	UserService       *users.UserService
	NoteService       *note.NoteService
	AuthService       *auth.AuthService
	UserConfigService *user_config.UserConfigService
}

var dbSet = wire.NewSet(database.InitDB, wire.Bind(new(database.IDbProvider), new(*database.DbProvider)))

var configSet = wire.NewSet(config.GetCfg, wire.Bind(new(database.IDbConfig), new(*config.Config)))

var repositorySet = wire.NewSet(repositories.NewUserRepository, repositories.NewAuthRepository, repositories.NewNoteRepository, repositories.NewUserConfigRepository)

var serviceSet = wire.NewSet(users.NewUserService, auth.NewAuthService, note.NewNoteService, user_config.NewUserConfigService)

func getTestContext() context.Context {
	return context.Background()
}
