// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewNote struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewUserConfig struct {
	IsDarkMode bool `json:"isDarkMode"`
	IsListMode bool `json:"isListMode"`
}

type Note struct {
	ID      int    `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	User    *User  `json:"user"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type UpdateUserConfig struct {
	IsDarkMode bool `json:"isDarkMode"`
	IsListMode bool `json:"isListMode"`
}

type User struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserConfig struct {
	ID         int   `json:"id"`
	IsDarkMode bool  `json:"isDarkMode"`
	IsListMode bool  `json:"isListMode"`
	User       *User `json:"user"`
}
