// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewNote struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewUser struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type NewUserConfig struct {
	IsDarkMode bool `json:"isDarkMode"`
	IsListMode bool `json:"isListMode"`
	FkUser     int  `json:"fkUser"`
}

type Note struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	User    *User  `json:"user"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserConfig struct {
	ID         string `json:"id"`
	IsDarkMode bool   `json:"isDarkMode"`
	IsListMode bool   `json:"isListMode"`
	User       *User  `json:"user"`
}
