CREATE TABLE IF NOT EXISTS user_config(
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  isDarkMode BOOL DEFAULT FALSE,
  isListMode BOOL DEFAULT TRUE,
  fk_user INT NOT NULL UNIQUE,
  FOREIGN KEY (fk_user) REFERENCES Users(ID) ,
  PRIMARY KEY (ID)
)